import { debugData } from "../utils/debugData";
import { VisibilityProvider } from "../providers/VisibilityProvider";
import DataHandler from "../DataHandler";
import ShopInterface from "./ShopInterface";
import { ShopItem } from "../types/ShopItem";

export default function App() {
	DataHandler();

	return (
		<VisibilityProvider>
			<div className="dark flex h-screen w-screen items-center justify-center">
				<div className="h-[82vh] w-3/4 bg-neutral-900/[0.97] p-4 transition-all">
					<ShopInterface />
				</div>
			</div>
		</VisibilityProvider>
	);
}

debugData([
	{
		action: "setVisible",
		data: true,
	},
]);

debugData([
	{
		action: "setCurrentShop",
		data: {
			shop: "247supermarket",
			label: "24/7 Supermarket",
			location: 1,
		},
	},
]);

debugData([
	{
		action: "setSelfData",
		data: {
			money: {
				Cash: 50.89,
				Bank: 200001.32,
			},
			weight: 1400,
			maxWeight: 14000,
			licenses: {
				weapon: true,
			},
		},
	},
]);

debugData([
	{
		action: "setShopItems",
		data: [
			{
				name: "redwood",
				category: "Redwood Wights Pack Long",
				label: "Redwood Wights Pack Long",
				price: 2,
				weight: 100,
				count: 23,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/egochaser.png",
			},
			{
				name: "egochaser",
				category: "Food",
				label: "Ego Chaser",
				price: 2,
				count: 5,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/egochaser.png",
			},
			{
				name: "steak",
				category: "Food",
				label: "Steak",
				price: 2,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/steak.png",
			},
			{
				name: "sparklng water",
				category: "Drink",
				label: "Crystal Clear Sparkling Water",
				price: 1,
				weight: 50,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/sparkling_water.png",
			},
			{
				name: "spots watch",
				category: "Accessory",
				label: "Sports Watch",
				price: 25,
				weight: 200,
				count: 3,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/sports_watch.png",
				license: "accessory",
			},
			{
				name: "gamng mouse",
				category: "Electronics",
				label: "Gaming Mouse",
				price: 35,
				weight: 150,
				count: 5,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/gaming_mouse.png",
			},
			{
				name: "chocolte bar",
				category: "Food",
				label: "Deluxe Chocolate Bar",
				price: 3,
				weight: 95,
				count: 15,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/chocolate_bar.png",
			},
			{
				name: "basebal cap",
				category: "Clothing",
				label: "Baseball Cap",
				price: 15,
				weight: 80,
				count: 20,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/baseball_cap.png",
			},
			{
				name: "artisan cof2ee",
				category: "Drink",
				label: "Artisan Coffee Beans",
				price: 15,
				weight: 500,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/artisan_coffee.png",
			},
			{
				name: "vintage sunglsses",
				category: "Accessory",
				label: "Vintage Sunglasses",
				price: 50,
				weight: 100,
				count: 4,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/vintage_sunglasses.png",
			},
			{
				name: "wireless headphnes",
				category: "Electronics",
				label: "Wireless Headphones",
				price: 120,
				weight: 250,
				count: 5,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/wireless_headphones.png",
			},
			{
				name: "organic granola bar1",
				category: "Food",
				label: "Organic Granola Bars",
				price: 5,
				weight: 50,
				count: 20,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/organic_granola_bars.png",
			},
			{
				name: "runnng shoes",
				category: "Clothing",
				label: "Running Shoes",
				price: 80,
				weight: 1000,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/running_shoes.png",
			},
			{
				name: "e-reade",
				category: "Electronics",
				label: "E-Reader",
				price: 130,
				weight: 300,
				count: 7,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/e_reader.png",
			},
			{
				name: "stek",
				category: "Food",
				label: "Steak",
				price: 2,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/steak.png",
			},
			{
				name: "sprkling water",
				category: "Drink",
				label: "Crystal Clear Sparkling Water",
				price: 1,
				weight: 50,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/sparkling_water.png",
			},
			{
				name: "sprts watch",
				category: "Accessory",
				label: "Sports Watch",
				price: 25,
				weight: 200,
				count: 3,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/sports_watch.png",
				license: "accessory",
			},
			{
				name: "ga2mng mouse",
				category: "Electronics",
				label: "Gaming Mouse",
				price: 35,
				weight: 150,
				count: 5,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/gaming_mouse.png",
			},
			{
				name: "chocoate bar",
				category: "Food",
				label: "Deluxe Chocolate Bar",
				price: 3,
				weight: 95,
				count: 15,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/chocolate_bar.png",
			},
			{
				name: "baseall cap",
				category: "Clothing",
				label: "Baseball Cap",
				price: 15,
				weight: 80,
				count: 20,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/baseball_cap.png",
			},
			{
				name: "artisan cofee",
				category: "Drink",
				label: "Artisan Coffee Beans",
				price: 15,
				weight: 500,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/artisan_coffee.png",
			},
			{
				name: "vintage sunlsses",
				category: "Accessory",
				label: "Vintage Sunglasses",
				price: 50,
				weight: 100,
				count: 4,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/vintage_sunglasses.png",
			},
			{
				name: "wireless headphones",
				category: "Electronics",
				label: "Wireless Headphones",
				price: 120,
				weight: 250,
				count: 5,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/wireless_headphones.png",
			},
			{
				name: "organic granola bars1",
				category: "Food",
				label: "Organic Granola Bars",
				price: 5,
				weight: 50,
				count: 20,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/organic_granola_bars.png",
			},
			{
				name: "running shoes",
				category: "Clothing",
				label: "Running Shoes",
				price: 80,
				weight: 1000,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/running_shoes.png",
			},
			{
				name: "e-reader",
				category: "Electronics",
				label: "E-Reader",
				price: 130,
				weight: 300,
				count: 7,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/e_reader.png",
			},
			{
				name: "gourmet cheese",
				category: "Food",
				label: "Gourmet Cheese",
				price: 20,
				weight: 200,
				count: 15,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/gourmet_cheese.png",
			},
			{
				name: "smartwatch",
				category: "Electronics",
				label: "Smartwatch",
				price: 199,
				weight: 150,
				count: 6,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/smartwatch.png",
			},
			{
				name: "professional camera",
				category: "Electronics",
				label: "Professional Camera",
				price: 850,
				weight: 1200,
				count: 3,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/professional_camera.png",
			},
			{
				name: "yoga mat",
				category: "Accessory",
				label: "Yoga Mat",
				price: 25,
				weight: 900,
				count: 12,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/yoga_mat.png",
			},
			{
				name: "bluetooth speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "backpack",
				category: "Accessory",
				label: "Backpack",
				price: 70,
				weight: 500,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/backpack.png",
			},
			{
				name: "redwoo",
				category: "Food",
				label: "Redwood",
				price: 2,
				count: 100,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/redwood.png",
			},
			{
				name: "running sh3oes",
				category: "Clothing",
				label: "Running Shoes",
				price: 80,
				weight: 1000,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/running_shoes.png",
			},
			{
				name: "e-read2er",
				category: "Electronics",
				label: "E-Reader",
				price: 130,
				weight: 300,
				count: 7,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/e_reader.png",
			},
			{
				name: "gourm1et cheese",
				category: "Food",
				label: "Gourmet Cheese",
				price: 20,
				weight: 200,
				count: 15,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/gourmet_cheese.png",
			},
			{
				name: "sm3artwatch",
				category: "Electronics",
				label: "Smartwatch",
				price: 199,
				weight: 150,
				count: 6,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/smartwatch.png",
			},
			{
				name: "profe1ssional camera",
				category: "Electronics",
				label: "Professional Camera",
				price: 850,
				weight: 1200,
				count: 3,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/professional_camera.png",
			},
			{
				name: "yoga 3mat",
				category: "Accessory",
				label: "Yoga Mat",
				price: 25,
				weight: 900,
				count: 12,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/yoga_mat.png",
			},
			{
				name: "bluetoot1h speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "backp3ack",
				category: "Accessory",
				label: "Backpack",
				price: 70,
				weight: 500,
				count: 10,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/backpack.png",
			},
			{
				name: "blue1toot1h speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "bluetoo2t1h speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "bluetoot15h speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "bluetoot1h spe6aker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "bluetoot1h spe41aker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "blueto21ot1h speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "blueto12ot1h speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "bluetoo32t1h speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
			{
				name: "blu1etoot1h speaker",
				category: "Electronics",
				label: "Bluetooth Speaker",
				price: 60,
				weight: 400,
				count: 8,
				imagePath: "https://files.jellyton.me/ShareX/2024/02/bluetooth_speaker.png",
			},
		] as ShopItem[],
	},
]);
